//go:build ignore

// Copyright 2026 The go-qrl Authors
// This file is part of the go-qrl library.
//
// The go-qrl library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-qrl library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-qrl library. If not, see <http://www.gnu.org/licenses/>.

// generate_emitter_js converts the checked-in Hyperion ABI and bytecode into
// the JavaScript fixture consumed by the embedded web3 console tests.
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

const compilerCommit = "f2e6ae7a59e8dafc23a2f34164fdd26180cec2dd"

func main() {
	abi, err := os.ReadFile("EventEmitter.abi")
	if err != nil {
		fatalf("read ABI: %v", err)
	}
	abi = bytes.TrimSpace(abi)
	if !json.Valid(abi) {
		fatalf("EventEmitter.abi is not valid JSON")
	}

	bin, err := os.ReadFile("EventEmitter.bin")
	if err != nil {
		fatalf("read bytecode: %v", err)
	}
	binHex := strings.TrimSpace(string(bin))
	if _, err := hex.DecodeString(binHex); err != nil {
		fatalf("EventEmitter.bin is not valid even-length hex: %v", err)
	}

	fixture := fmt.Sprintf(`// Code generated by generate_emitter_js.go; DO NOT EDIT.
//
// Source: EventEmitter.hyp
// Compiler: github.com/cyyber/hyperion@%s
// Regenerate with the VM64 hypc, then rebuild this wrapper:
//
//     hypc --bin --abi --storage-layout --no-cbor-metadata -o . --overwrite EventEmitter.hyp
//     go run generate_emitter_js.go
var EMITTER = {
  signature: "Deployed(uint256)",
  value: 1337,
  abi: %s,
  bin: "0x%s"
};
`, compilerCommit, abi, binHex)
	if err := os.WriteFile("emitter.js", []byte(fixture), 0o644); err != nil {
		fatalf("write JavaScript fixture: %v", err)
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "generate emitter fixture: "+format+"\n", args...)
	os.Exit(1)
}
