// End-to-end event/topic round-trip suite, run through `gqrl attach --exec`
// by run_tests.sh. Deploys the precompiled Hyperion contract from
// fixtures/emitter.js — its constructor emits Deployed(uint256) — using a
// transaction pre-signed by txsigner from a prefunded dev account (the
// console has no account management), then asserts that the emitted topic0
// is keccak256(signature) LEFT-aligned in the 64-byte topic (hash||zeros)
// and that both the contract event filter and a raw qrl.getLogs filter using
// the full VM64 topic match it.
//
// run_tests.sh generates tests/.params.js (var PARAMS = {...};) with the
// signed deployment transaction before running this suite.

var _pass = 0;
var _fail = 0;

function check(desc, fn) {
    try {
        if (fn() === false) {
            throw new Error("assertion returned false");
        }
        _pass++;
        console.log("PASS: " + desc);
    } catch (e) {
        _fail++;
        console.log("FAIL: " + desc + " -- " + e);
    }
}

function zeros(n) {
    return new Array(n + 1).join("0");
}

// loadScript throws when the file is missing or does not compile.
var _abort = false;
try {
    loadScript("fixtures/emitter.js");
    loadScript(".params.js"); // generated by run_tests.sh
} catch (e) {
    console.log("FAIL: could not load test scripts -- " + e);
    _fail++;
    _abort = true;
}

var receipt = null;

if (!_abort) {
    check("prefunded account matches the signed transaction", function () {
        if (!/^Q[0-9a-fA-F]{128}$/.test(PARAMS.address)) {
            throw new Error("unexpected deployer address: " + PARAMS.address);
        }
        var balance = qrl.getBalance(PARAMS.address);
        if (!(balance > 0)) {
            throw new Error("deployer " + PARAMS.address + " has zero balance; check network_params.yaml prefunded_accounts");
        }
        return true;
    });

    check("deployment transaction is accepted and mined", function () {
        var txHash = qrl.sendRawTransaction(PARAMS.rawTransaction);
        if (txHash !== PARAMS.txHash) {
            throw new Error("tx hash mismatch: have " + txHash + " want " + PARAMS.txHash);
        }
        // Mainnet-preset slots are 60s, so allow a few slots.
        for (var i = 0; i < 60; i++) {
            receipt = qrl.getTransactionReceipt(txHash);
            if (receipt !== null && receipt.blockNumber !== null) {
                break;
            }
            admin.sleep(5);
        }
        if (receipt === null || receipt.blockNumber === null) {
            throw new Error("transaction not mined within timeout");
        }
        if (Number(receipt.status) !== 1) {
            throw new Error("deployment reverted, status " + receipt.status);
        }
        if (!receipt.contractAddress) {
            throw new Error("receipt has no contractAddress");
        }
        return true;
    });
}

if (receipt !== null) {
    var sigHash = web3.sha3(EMITTER.signature); // 0x + 64 hex chars
    var expectedTopic = sigHash + zeros(64);    // left-aligned in 64-byte topic

    check("transaction and block APIs expose the mined deployment", function () {
        var tx = qrl.getTransaction(PARAMS.txHash);
        if (tx === null) {
            throw new Error("qrl.getTransaction returned null");
        }
        if (tx.hash !== PARAMS.txHash || tx.from !== PARAMS.address) {
            throw new Error("unexpected transaction: " + JSON.stringify(tx));
        }
        if (tx.to !== null) {
            throw new Error("deployment transaction has non-null to: " + tx.to);
        }

        var blockWithHashes = qrl.getBlock(receipt.blockNumber, false);
        var blockWithTxs = qrl.getBlock(receipt.blockNumber, true);
        if (blockWithHashes.transactions.indexOf(PARAMS.txHash) < 0) {
            throw new Error("block hash list does not include deployment tx");
        }
        var found = false;
        for (var i = 0; i < blockWithTxs.transactions.length; i++) {
            if (blockWithTxs.transactions[i].hash === PARAMS.txHash) {
                found = true;
                break;
            }
        }
        if (!found) {
            throw new Error("full transaction block does not include deployment tx object");
        }
        return true;
    });

    check("block receipt API exposes the deployment log", function () {
        var receipts = qrl.getBlockReceipts(receipt.blockNumber);
        if (!(receipts instanceof Array)) {
            throw new Error("qrl.getBlockReceipts did not return an array");
        }
        for (var i = 0; i < receipts.length; i++) {
            if (receipts[i].transactionHash === PARAMS.txHash) {
                if (receipts[i].logs.length !== 1) {
                    throw new Error("expected one log in block receipt, got " + receipts[i].logs.length);
                }
                if (receipts[i].logs[0].topics[0] !== expectedTopic) {
                    throw new Error("receipt topic mismatch: " + receipts[i].logs[0].topics[0]);
                }
                return true;
            }
        }
        throw new Error("qrl.getBlockReceipts did not include deployment receipt");
    });

    check("emitted topic0 is keccak256(signature) left-aligned (hash||zeros)", function () {
        if (receipt.logs.length !== 1) {
            throw new Error("expected 1 log, got " + receipt.logs.length);
        }
        var topic0 = receipt.logs[0].topics[0];
        if (topic0 !== expectedTopic) {
            throw new Error("have " + topic0 + " want " + expectedTopic);
        }
        return true;
    });

    check("VM64 event data encodes the value in a 64-byte word", function () {
        var data = receipt.logs[0].data;
        var expected = "0x" + zeros(125) + "539"; // 1337
        if (data !== expected) {
            throw new Error("have " + data + " want " + expected);
        }
        return true;
    });

    var contract = qrl.contract(EMITTER.abi).at(receipt.contractAddress);

    check("contract event filter matches the emitted log", function () {
        var filter = contract.Deployed({}, {
            fromBlock: web3.toHex(receipt.blockNumber),
            toBlock: web3.toHex(receipt.blockNumber)
        });
        var events = filter.get();
        if (events.length !== 1) {
            throw new Error("expected 1 event, got " + events.length);
        }
        if (events[0].transactionHash !== receipt.transactionHash) {
            throw new Error("event from unexpected transaction: " + events[0].transactionHash);
        }
        return true;
    });

    check("contract event filter decodes the emitted value", function () {
        var filter = contract.Deployed({}, {
            fromBlock: web3.toHex(receipt.blockNumber),
            toBlock: web3.toHex(receipt.blockNumber)
        });
        var events = filter.get();
        if (events.length === 1 && Number(events[0].args.value) === EMITTER.value) {
            return true;
        }
        throw new Error("unexpected decoded args: " + JSON.stringify(events.length === 1 ? events[0].args : events));
    });

    check("qrl.getLogs with the full VM64 signature topic matches", function () {
        var logs = qrl.getLogs({
            fromBlock: web3.toHex(receipt.blockNumber),
            toBlock: web3.toHex(receipt.blockNumber),
            topics: [expectedTopic]
        });
        if (logs.length !== 1) {
            throw new Error("expected 1 log, got " + logs.length);
        }
        if (logs[0].address !== receipt.contractAddress) {
            throw new Error("log from unexpected address: " + logs[0].address);
        }
        if (logs[0].topics[0] !== expectedTopic) {
            throw new Error("have topic " + logs[0].topics[0] + " want " + expectedTopic);
        }
        return true;
    });

    check("qrl.getLogs with only the raw 32-byte signature hash is rejected", function () {
        try {
            qrl.getLogs({
                fromBlock: web3.toHex(receipt.blockNumber),
                toBlock: web3.toHex(receipt.blockNumber),
                topics: [sigHash]
            });
        } catch (e) {
            return true;
        }
        throw new Error("expected an error");
    });
}

console.log("SUITE event_roundtrip: " + (_fail === 0 ? "PASSED" : "FAILED") +
    " (" + _pass + "/" + (_pass + _fail) + " checks)");
